/** @param {NS} ns */
export async function main(ns) {
    // ===== CONFIGURATION =====
    // Get these from Trillium Options -> ETAPI
    const TRILIUM_URL = 'http://localhost:8080';  // Change to your Trilium URL
    const ETAPI_TOKEN = 'YOUR_TOKEN_HERE';        // Get from Options -> ETAPI
    const PARENT_NOTE_ID = 'root';                // Where to create the network map
    
    // Check if config is set
    if (ETAPI_TOKEN === 'YOUR_TOKEN_HERE') {
        ns.tprint('ERROR: Please configure TRILIUM_URL and ETAPI_TOKEN in the script!');
        ns.tprint('Get your ETAPI token from Trillium: Options -> ETAPI');
        return;
    }
    
    const visited = new Set();
    const noteMap = new Map(); // Map server names to note IDs
    
    // Create a note in Trillium via ETAPI
    async function createNote(title, content, parentNoteId) {
        const payload = {
            title: title,
            type: 'text',
            content: content,
            parentNoteId: parentNoteId
        };
        
        const response = await fetch(`${TRILIUM_URL}/etapi/create-note`, {
            method: 'POST',
            headers: {
                'Authorization': ETAPI_TOKEN,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(payload)
        });
        
        if (!response.ok) {
            ns.tprint(`ERROR: Failed to create note "${title}": ${response.status}`);
            return null;
        }
        
        const data = await response.json();
        return data.note.noteId;
    }
    
    // Recursively map network and create notes
    async function mapNetwork(server, parentNoteId, depth = 0) {
        if (visited.has(server)) return;
        visited.add(server);
        
        // Get server info
        const hasRoot = ns.hasRootAccess(server);
        const money = ns.getServerMoneyAvailable(server);
        const maxMoney = ns.getServerMaxMoney(server);
        const security = ns.getServerSecurityLevel(server);
        const reqHack = ns.getServerRequiredHackingLevel(server);
        const minSec = ns.getServerMinSecurityLevel(server);
        const ports = ns.getServerNumPortsRequired(server);
        const ram = ns.getServerMaxRam(server);
        
        // Build note content with server details
        let content = `<h3>Server Information</h3>`;
        content += `<ul>`;
        content += `<li><strong>Hostname:</strong> ${server}</li>`;
        content += `<li><strong>Root Access:</strong> ${hasRoot ? '✓ Yes' : '✗ No'}</li>`;
        content += `<li><strong>Required Hacking Level:</strong> ${reqHack}</li>`;
        content += `<li><strong>Ports Required:</strong> ${ports}</li>`;
        content += `<li><strong>RAM:</strong> ${ram} GB</li>`;
        
        if (maxMoney > 0) {
            content += `<li><strong>Money:</strong> $${ns.formatNumber(money)} / $${ns.formatNumber(maxMoney)}</li>`;
            content += `<li><strong>Growth:</strong> ${ns.getServerGrowth(server)}</li>`;
        }
        
        content += `<li><strong>Security:</strong> ${security.toFixed(2)} (min: ${minSec})</li>`;
        content += `</ul>`;
        
        // Create note for this server
        const noteTitle = server === 'home' ? '🏠 home' : server;
        ns.tprint(`Creating note: ${'  '.repeat(depth)}${noteTitle}`);
        
        const noteId = await createNote(noteTitle, content, parentNoteId);
        if (!noteId) return;
        
        noteMap.set(server, noteId);
        
        // Recursively map connected servers as child notes
        const connections = ns.scan(server);
        for (const connected of connections) {
            if (!visited.has(connected)) {
                await mapNetwork(connected, noteId, depth + 1);
            }
        }
    }
    
    // Create main network map note
    ns.tprint('Creating Bitburner Network Map in Trillium...');
    const mainNoteId = await createNote(
        '🌐 Bitburner Network Map',
        '<p>Network map generated by Bitburner script</p>',
        PARENT_NOTE_ID
    );
    
    if (!mainNoteId) {
        ns.tprint('ERROR: Failed to create main note. Check your configuration.');
        return;
    }
    
    // Start mapping from home
    await mapNetwork('home', mainNoteId);
    
    ns.tprint('\n✓ Network map created successfully in Trillium!');
    ns.tprint(`Total servers mapped: ${visited.size}`);
    ns.tprint(`\nOpen Trillium and navigate to the "🌐 Bitburner Network Map" note.`);
}
